### ISSUE TITLE
Wrong textcolor in dropdown view on Android 4.x devices

### ISSUE THREAD

**Issue by chrisonline** [SimplicityApks/ReminderDatePicker#12] opened 2015-01-08 12:47 UTC
On Android 4.x devices I get wrong textcolor in the dropdown view.
On Android 5.x it works.

![image](https://cloud.githubusercontent.com/assets/2077218/5662682/bfcda914-973c-11e4-89b7-d16806a01e84.png)

Update:
It works in the emulator if I change:
android:textColor="?android:textColorSecondaryInverse"/> to android:textColor="?android:textColorSecondary"/> in the twin_text_dropdown_item_dark.xml!

But now the twin_text_dropdown_item and twin_text_dropdown_item_dark are completly the same.
So no need for two xml's !?

**Comment by SimplicityApks** [comment] 2015-01-09 19:59
I think you can blame ActionBarCompat for this one, I noticed that bug while migrating to Lollipop, and "fixed" it [here](https://github.com/SimplicityApks/ReminderDatePicker/commit/9bb90831a5a1a6f8650f396b4da37afd55271d9b). As the fix is still functional with the sample app from the Play Store (at least on KitKat), I assume the guys at ActionBarCompat have fixed their backgrounds in version 21.0.3 and therefore made my fix break it again ;). 

I'll probably just have to revert my "fix"...

**Comment by SimplicityApks** [comment] 2015-01-10 16:55
Ok so this is very strange, when I compile the current sample sources with ActionBarCompat updated to version 21.0.3 and launch it in an Android 4.4.4 emulator or on a KitKat device, everything is still fully functional with a white spinner background. It looks like this:
![whitespinnerbackground_emulator](https://cloud.githubusercontent.com/assets/5840627/5692322/2ca51a3a-98f1-11e4-8e4d-9cfad1b40b7a.png)

So I can't really do anything about it since I don't see the black background (which would be nice to have). Can you clarify on what device and Android version you are getting the image posted above? And also, can you try to reproduce it in an emulator with the sample app so we can see what is different?

The only thing I can imagine what is wrong here might be some themes in your styles.xml or rom overriding the spinner background... if you have such a modification, let me know ;).

**Comment by chrisonline** [comment] 2015-01-12 16:22
OK I still use the r20 of the appcompat library!
So if the r21 breaks it I have to add your fix again if I use the r21 :-)

Thanks anyway.

**Comment by SimplicityApks** [comment] 2015-01-20 20:05
I'll close this as well since it is obviously only occuring with the outdated ABC lib.

**Closed by SimplicityApks** 2015-01-20 20:05 UTC
Labels: bug
