### ISSUE TITLE
API 8 dark theme wrong button color

### ISSUE THREAD

**Issue by chrisonline** [SimplicityApks/ReminderDatePicker#14] opened 2015-01-28 12:37 UTC
On API 8 devices with dark theme the text on the button is white.
Should be black.

I've fixed it on my side with adding a layout-v11 and change the xml in the layout folder.
Instead of textColorPrimary I use primary_text_light_nodisable! 
The same as the standard API 8 uses on buttons.

layout-v11:
<TextView
        android:id="@android:id/text1"
        style="?android:attr/spinnerItemStyle"
        android:singleLine="true"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:ellipsize="marquee"
        android:textAlignment="inherit"
        android:textColor="?android:textColorPrimary"/>

layout:
<TextView
        android:id="@android:id/text1"
        style="?android:attr/spinnerItemStyle"
        android:singleLine="true"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:ellipsize="marquee"
        android:textAlignment="inherit"
        android:textColor="@android:color/primary_text_light_nodisable" />

**Comment by SimplicityApks** [comment] 2015-01-28 20:49
I'm unable to reproduce this issue in my Froyo emulator, I see a dark button background and thus a white text makes perfect sense:
![reminderdatepickerapi8dark](https://cloud.githubusercontent.com/assets/5840627/5946592/4f5a88b8-a737-11e4-99e9-c628fc5fa13e.png)

I guess this occurs because of the older version of appcompat that you're using, or some skin an your device.

**Comment by chrisonline** [comment] 2015-01-30 06:37
Ok strange. Because I see not a borderless button on api  8.
Will check this. Sorry to bother you.

**Comment by chrisonline** [comment] 2015-02-08 14:48
I don't get it why I see the standard spinner (button like) on API8 and your sample have spinner style of Android 4.x!

In reminder_date_picker.xml you don't set a "Appcombat Style" to the spinner.
So why is it displayed in API8 like an Android 4.x spinner? Can you help?

**Comment by SimplicityApks** [comment] 2015-02-08 15:23
I guess this is because the sample app uses 
    `<style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">`
on all API levels. When you use a Theme.Light or something like that on older android versions, it will use the system drawables and not Appcompat's. So beware of having different styles.xml in values-v11 and values-v14! And it is just the drawable though, there will still be a dialog instead of a popup menu on Froyo.

You don't need to set a specific style for your widgets, having the theme set up correctly should work on its own.

**Comment by chrisonline** [comment] 2015-02-09 19:03
I have "<style name="Theme.Holo.Light" parent="@style/Theme.AppCompat.Light">" and this is on all API levels. I don't have themes in values-v9 or something else. So it uses AppCompat.Light.
Thanks, I will check your sample app again if I find the problem.

**Comment by SimplicityApks** [comment] 2015-03-07 16:20
I guess I can close this one as well as it doesn't appear to be a problem with the library and I still can't reproduce it.

**Closed by SimplicityApks** 2015-03-07 16:20 UTC
